status = [
  'integration-tests (ruby 2.6)',
  'integration-tests (ruby 2.7)',
  'integration-tests (ruby 3.0)',
  'integration-tests (ruby 3.1)',
  'linter-check'
]
# 1 hour timeout
timeout-sec = 3600
