version: "3.8"

volumes:
  bundle:

services:
  package:
    image: ruby:3.0
    tty: true
    stdin_open: true
    working_dir: /home/app
    environment:
      - MEILISEARCH_HOST=meilisearch
      - MEILISEARCH_PORT=7700
      - BUNDLE_PATH=/vendor/bundle
    ports:
      - "3001:3000"
    volumes:
      - ./:/home/app
      - bundle:/vendor/bundle
    links:
      - meilisearch

  meilisearch:
    image: getmeili/meilisearch:latest
    tty: true
    stdin_open: true
    container_name: meilisearch
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=masterKey
